name: Docker Image CI

on:
  push:
    branches: ['scalemote/prod']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build the Docker image
        run: docker build --file ./Dockerfile --tag scalemote/sdp-api:${{ github.sha }} .
      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          local-image: scalemote/sdp-api:${{ github.sha }}
          image: scalemote/sdp-api:${{ github.sha }}, scalemote/sdp-api:latest

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          container-name: ${{ secrets.ECS_SDP_CONTAINER_NAME }}
          image: scalemote/sdp-api:${{ github.sha }}, scalemote/sdp-api:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          service: ${{ secrets.ECS_SDP_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
          
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/sdp-task-definition.json
          container-name: ${{ secrets.ECS_TSS_CONTAINER_NAME }}
          image: scalemote/sdp-api:${{ github.sha }}, scalemote/sdp-api:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: .aws/tss-task-definition.json
          service: ${{ secrets.ECS_TSS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true

          